version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www/html/
    depends_on:
      - db

  db:
    build: ./mysql-docker
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456